linux-x86_64:
  stage: build
  image: registry.gitlab.com/fzwoch/obs-gstreamer/linux
  script:
    - meson --buildtype release linux
    - ninja -C linux
  artifacts:
    paths:
      - linux/gstreamer.so

macos-x86_64:
  stage: build
  image: registry.gitlab.com/fzwoch/obs-gstreamer/macos
  script:
    - echo "[binaries]" >> cross.txt
    - echo "c = 'x86_64-apple-darwin15-cc'" >> cross.txt
    - echo "cpp = 'x86_64-apple-darwin15-c++'" >> cross.txt
    - echo "ar = 'x86_64-apple-darwin15-ar'" >> cross.txt
    - echo "strip = 'x86_64-apple-darwin15-strip'" >> cross.txt
    - echo "pkgconfig = 'x86_64-apple-darwin15-pkg-config'" >> cross.txt

    - echo "[host_machine]" >> cross.txt
    - echo "system = 'darwin'" >> cross.txt
    - echo "cpu_family = 'x86_64'" >> cross.txt
    - echo "cpu = 'x86_64'" >> cross.txt
    - echo "endian = 'little'" >> cross.txt

    - export C_INCLUDE_PATH=/
    - export LIBRARY_PATH=/Applications/OBS.app/Contents/Resources/bin

    - meson --buildtype release --cross-file cross.txt macos
    - ninja -C macos
  artifacts:
    paths:
      - macos/gstreamer.dylib

windows-x86_64:
  stage: build
  image: registry.gitlab.com/fzwoch/obs-gstreamer/mingw
  script:
    - export PKG_CONFIG_PATH=/c/gstreamer/1.0/x86_64/lib/pkgconfig/

    - echo "[binaries]" >> cross.txt
    - echo "c = 'x86_64-w64-mingw32-gcc'" >> cross.txt
    - echo "cpp = 'x86_64-w64-mingw32-g++'" >> cross.txt
    - echo "ar = 'x86_64-w64-mingw32-ar'" >> cross.txt
    - echo "strip = 'x86_64-w64-mingw32-strip'" >> cross.txt
    - echo "pkgconfig = 'x86_64-w64-mingw32-pkg-config'" >> cross.txt
    - echo "windres = 'x86_64-w64-mingw32-windres'" >> cross.txt

    - echo "[host_machine]" >> cross.txt
    - echo "system = 'windows'" >> cross.txt
    - echo "cpu_family = 'x86_64'" >> cross.txt
    - echo "cpu = 'x86_64'" >> cross.txt
    - echo "endian = 'little'" >> cross.txt

    - export C_INCLUDE_PATH=/
    - export LIBRARY_PATH=/bin/64bit

    - meson --buildtype release --cross-file cross.txt windows
    - ninja -C windows
  artifacts:
    paths:
      - windows/gstreamer.dll
